---
- name: Configure banner
  arista.eos.eos_banner:
    banner: motd
    text:
      -------------------------------------
    
      Authorized Access Only - {{ inventory_hostname }}

      -------------------------------------
    state: present
  tags:
    - base_config