###swap this to showing dates so configs are not overwritten when run multiple times

---
- hosts: all
  connection: local
  gather_facts: yes

  tasks:
    - name: Backup running config
      eos_command:
        commands: "show running-config"
      register: output

    - name: Save backup to file
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "~/backups/{{ inventory_hostname }}_running_config_{{ ansible_date_time.date }}.txt"