---
- hosts: spines
  connection : local
  gather_facts: no

  tasks:
    - name: "Gather EVPN Summary"
      eos_command:
        commands: 'show evpn summary | json'
      register: evpn_summary

    - name: "Display EVPN Summary"
      debug:
        var: evpn_summary.results[0].stdout[0]
